services:
  adservice:
      build:
        context: ./src/adservice
        dockerfile: Dockerfile

      environment:
        PORT: 9555
        
      ports:
        - "9555:9555"
  cartservice:
      build:
        context: ./src/cartservice/src
        dockerfile: Dockerfile

      environment:
        PORT: 8080

      ports:
        - "8080:8080"

  checkoutservice:
      build:
        context: ./src/checkoutservice
        dockerfile: Dockerfile

      environment:
        PORT: 5050

        SHIPPING_SERVICE_ADDR: shippingservice:50051
        PRODUCT_CATALOG_SERVICE_ADDR: productcatalogservice:3550
        CART_SERVICE_ADDR: cartservice:8080
        CURRENCY_SERVICE_ADDR: currencyservice:3000
        EMAIL_SERVICE_ADDR: emailservice:8080
        PAYMENT_SERVICE_ADDR: paymentservice:3000

      ports:
        - "5050:5050"

  currencyservice:
      build:
        context: ./src/currencyservice
        dockerfile: Dockerfile
      
      environment:
        PORT: 3000

        DISABLE_PROFILER: 1
        
      ports:
        - "3000:3000"


  emailservice:
      build:
        context: ./src/emailservice
        dockerfile: Dockerfile
      
      environment:
        PORT: 8080
        
      ports:
        - "8081:8080"

  frontend:
      build:
        context: ./src/frontend
        dockerfile: Dockerfile

      environment:
        PORT: 8080

        PRODUCT_CATALOG_SERVICE_ADDR: productcatalogservice:3550
        CURRENCY_SERVICE_ADDR: currencyservice:3000
        CART_SERVICE_ADDR: cartservice:8080
        RECOMMENDATION_SERVICE_ADDR: recommendationservice:8080
        CHECKOUT_SERVICE_ADDR: checkoutservice:5050
        SHIPPING_SERVICE_ADDR: shippingservice:50051
        AD_SERVICE_ADDR: adservice:9555

      ports:
        - "8082:8080"

  shippingservice:
      build:
        context: ./src/shippingservice
        dockerfile: Dockerfile
      
      environment:
        PORT: 50051
        
      ports:
        - "50051:50051"
        
  loadgenerator:
      build:
        context: ./src/loadgenerator
        dockerfile: Dockerfile
      
      environment:
        LOCUST_SPAWN_RATE: 1
        LOCUST_USERS: 5
        LOCUST_HOST: http://frontend:8080      

      depends_on:
        - frontend
  recommendationservice:
      build:
        context: ./src/recommendationservice
        dockerfile: Dockerfile

      environment:
        PORT: 8080

        PRODUCT_CATALOG_SERVICE_ADDR: productcatalogservice:3550
        
      ports:
        - "8083:8080"
        
  productcatalogservice:
      build:
        context: ./src/productcatalogservice
        dockerfile: Dockerfile
      
      environment:
        PORT: 3550
        
      ports:
        - "3550:3550"
