services:
  adservice:
      build:
        context: ./src/adservice
        dockerfile: Dockerfile

      environment:
        PORT: 9555
        
      ports:
        - "9555:9555"
  cartservice:
      build:
        context: ./src/cartservice/src
        dockerfile: Dockerfile

      environment:
        PORT: 8080

      ports:
        - "8080:8080"

  checkoutservice:
      build:
        context: ./src/checkoutservice
        dockerfile: Dockerfile

      environment:
        PORT: 5050

        SHIPPING_SERVICE_ADDR: shippingservice:50051
        PRODUCT_CATALOG_SERVICE_ADDR: productcatalogservice:3550
        CART_SERVICE_ADDR: cartservice:8080
        CURRENCY_SERVICE_ADDR: currencyservice:3000
        EMAIL_SERVICE_ADDR: emailservice:8080
        PAYMENT_SERVICE_ADDR: paymentservice:3000

      ports:
        - "5050:5050"

  currencyservice:
      build:
        context: ./src/currencyservice
        dockerfile: Dockerfile
      
      environment:
        PORT: 3000

        DISABLE_PROFILER: 1
        
      ports:
        - "3000:3000"


  emailservice:
      build:
        context: ./src/emailservice
        dockerfile: Dockerfile
      
      environment:
        PORT: 8080
        
      ports:
        - "8081:8080"