on:
  push:
    branches:
      - main
    paths:
      - src/adservice/**

jobs:
  trigger-reusable:
    uses: ./.github/workflows/publish.yml
    secrets: inherit
    with:
      service: adservice
      context: ./src/adservice
      dockerfile: ./src/adservice/Dockerfile