on:
  push:
    branches:
      - main
    paths:
      - src/emailservice/**

jobs:
  trigger-reusable:
    uses: ./.github/workflows/publish.yml
    secrets: inherit
    with:
      service: emailservice
      context: ./src/emailservice
      dockerfile: ./src/emailservice/Dockerfile