on:
  push:
    branches:
      - main
    paths:
      - src/frontend/**

jobs:
  trigger-reusable:
    uses: ./.github/workflows/publish.yml
    secrets: inherit
    with:
      service: frontend
      context: ./src/frontend
      dockerfile: ./src/frontend/Dockerfile