on:
  push:
    branches:
      - main
    paths:
      - src/recommendationservice/**

jobs:
  trigger-reusable:
    uses: ./.github/workflows/publish.yml
    secrets: inherit
    with:
      service: recommendationservice
      context: ./src/recommendationservice
      dockerfile: ./src/recommendationservice/Dockerfile